Rem generate the files: tpgamefiles.dat, co8fixes.dat,  co8infra.dat and kotbfixes.dat in ..\tpdata 
Rem Note:  ..\tpdata\clearances.dat is checked in and not generated by this sciprt
set basedir=%~dp0
cd %basedir%

%basedir%..\dependencies\bin\datpack.exe tpgamefiles.dat %basedir%tpgamefiles
move /Y tpgamefiles.dat %basedir%..\tpdata\

%basedir%..\dependencies\bin\datpack.exe co8fixes.dat %basedir%co8fixes
move /Y co8fixes.dat %basedir%..\tpdata\

%basedir%..\dependencies\bin\datpack.exe co8infra.dat %basedir%co8infra
move /Y co8infra.dat %basedir%..\tpdata\

%basedir%..\dependencies\bin\datpack.exe kotbfixes.dat %basedir%kotbfixes
move /Y kotbfixes.dat %basedir%..\tpdata\

%basedir%..\dependencies\bin\datpack.exe palcov.dat %basedir%palcov
move /Y palcov.dat %basedir%..\tpdata\
