Rem generate the files: tpgamefiles.dat, co8fixes.dat,  co8infra.dat and kotbfixes.dat in ..\tpdata 
Rem Note:  ..\tpdata\clearances.dat is checked in and not generated by this sciprt
set basedir=%~dp0
cd %basedir%
cd tpgamefiles
%basedir%..\dependencies\bin\TioPack.exe /R tpgamefiles.dat scr\*.* dlg\*.* art\*.* mes\*.* rules\*.* sound\*.* tpmes\*.*
move /Y tpgamefiles.dat %basedir%..\tpdata\
cd ..
cd co8fixes
%basedir%..\dependencies\bin\TioPack.exe /R co8fixes.dat scr\*.* dlg\*.* art\*.* mes\*.* rules\*.* sound\*.* tpmes\*.*
move /Y co8fixes.dat %basedir%..\tpdata\
cd ..
cd co8infra
%basedir%..\dependencies\bin\TioPack.exe /R co8infra.dat scr\*.* dlg\*.* art\*.* mes\*.* rules\*.* sound\*.* tpmes\*.*
move /Y co8infra.dat %basedir%..\tpdata\
cd ..
cd kotbfixes
%basedir%..\dependencies\bin\TioPack.exe /R kotbfixes.dat scr\*.* dlg\*.* art\*.* mes\*.* rules\*.* sound\*.* tpmes\*.*
move /Y kotbfixes.dat %basedir%..\tpdata\
cd ..\