Rem generate the files: tpgamefiles.dat, co8fixes.dat,  co8infra.dat and kotbfixes.dat in ..\tpdata 
Rem Note:  ..\tpdata\clearances.dat is checked in and not generated by this sciprt
set basedir=%~dp0

REM removing this for now because it caused nothing but trouble


REM cd %basedir%
REM REM cd tpgamefiles
REM %basedir%..\dependencies\bin\datpack.exe tpgamefiles.dat %basedir%tpgamefiles
REM move /Y tpgamefiles.dat %basedir%..\tpdata\
REM REM cd ..
REM REM cd co8fixes
REM %basedir%..\dependencies\bin\datpack.exe co8fixes.dat %basedir%co8fixes
REM move /Y co8fixes.dat %basedir%..\tpdata\
REM REM cd ..
REM REM cd co8infra
REM %basedir%..\dependencies\bin\datpack.exe co8infra.dat %basedir%co8infra
REM move /Y co8infra.dat %basedir%..\tpdata\
REM REM cd ..
REM REM cd kotbfixes
REM %basedir%..\dependencies\bin\datpack.exe kotbfixes.dat %basedir%kotbfixes
REM move /Y kotbfixes.dat %basedir%..\tpdata\
REM cd ..\